# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  tests:
    runs-on: "${{ matrix.platform }}"
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies.
      run: |
          make
        
    - name: Test with pytest.
      run: |
        make test
        
    - name: Lint with mypy and flake8.
      run: |
        make lint
  
  package:
    runs-on: "${{ matrix.platform }}"
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies.
      run: |
          pip install --upgrade pip twine
        
    - name: Build the package.
      run: |
        make build

    - name: Check twine.
      run: python -m twine check dist/*
